unique_ids:
  assets:
    standard-page.html: FK5RW5RTDP5DHJF4DAWK2VQ7FY2KF25M
    theme.css: HDDRK5SM54WJWKQMRENHPOG6BYTMTPOQ
  forms:
    Form1: ZYAICP3JYBE7CMLCJUP5WPHOZIEB75NE
  modules: {}
  scripts: {}
  server_modules: {}
